CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE public.admission_documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text,
    embedding vector(1536),
    category text,
    source_file text
);

CREATE INDEX idx_admission_embedding_hnsw
ON public.admission_documents
USING hnsw (embedding vector_cosine_ops);